# BASE PATHS FOR CONFIGURATIONS AND BUILD/INSTALL LOCATIONS
BUILDDIR    : ${HOME}/apps
INSTALLDIR  : ${HOME}/opt
COMPUTER    : wigner


# VERSIONS OF BASIC APPS
OMPI_VER  : 4.1.3
GSL1_VER  : 1.9
GSL2_VER  : 2.7
FFTW2_VER : 2.1.5
FFTW3_VER : 3.3.10
HWLOC_VER : 2.6.0
HDF5_VER  : 1.10.6


# TECHNICAL PARAMETERS
N_CPUS        : 8