# BASE PATHS FOR CONFIGURATIONS AND BUILD/INSTALL LOCATIONS
BUILDDIR    : ${HOME}/apps
INSTALLDIR  : ${HOME}/opt
BUILDSYS    : ${ENVDIR}/build
COMPUTER    : home

# VERSIONS OF BASIC APPS
GV_VER      : 1.1.2

# TECHNICAL PARAMETERS
N_CPUS      : 32